name: Deploy to VPS

on:
  push:
    branches:
      - main # ให้ workflow ทำงานเมื่อมีการ push ไปที่ branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart customer_app
